version: '3'
services:
  frontend:
    build:
      context: ./chess-front
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./chess-front:/app
      - /app/node_modules
    container_name: frontend
